### ISSUE TITLE
Add new field in the aws_ecr_repository to show scanning configurations using batch-get-repository-scanning-configuration method

### ISSUE THREAD

**Issue by jeffreymp17** [turbot/steampipe-plugin-aws#1716]
**Description**

In the `aws_ecr_repository` table, the image_scanning_configuration field is used to validate if ScanOnPush is enabled by accessing the JSON value that is called like this, but going deeper into this we saw that if we enable the Continuous Scanning option in private repositories all private repositories will have the option to scan _CONTINUOUS_ and the value of _ScanOnPush_ will continue with the previous state and now the value is scanning continues

**Describe the solution you'd like**
For that reason above, we believe that this `[batch-get-repository-scanning-configuration](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_BatchGetRepositoryScanningConfiguration.html)` method returns the accurate data to show configurations about scanning, here an example of the method response:

```
failures: []
scanningConfigurations:
- appliedScanFilters:
  - filter: '*'
    filterType: WILDCARD
  repositoryArn: arn:aws:ecr:us-east-1:123456789:repository/scanning-on-push-disabled
  repositoryName: scanning-on-push-disabled
  scanFrequency: CONTINUOUS_SCAN
  scanOnPush: false
```

The solution is to create a field that populates the information the method above provides as a JSON field called `repository-scanning-configuration` due the data is more exact in terms to show if scanning is enabled and what type is configured.

**Describe alternatives you've considered**

**Additional context**
To enable continuos scanning in the private repositories, this as image reference for it 
<img width="999" alt="Screenshot 2023-04-21 at 10 13 43" src="https://user-images.githubusercontent.com/30936236/234042178-3bc64b01-5377-4d8d-b753-7b152136d582.png">
